apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example
  labels:
    app: example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  strategy: {}
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: bcheck-api
        image: 273563728071.dkr.ecr.ap-northeast-2.amazonaws.com/repo-example-jenkins:v47
        ports:
         - containerPort: 8080
        resources: {}