apiVersion: v1
kind: Service
metadata:
  name: example-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/healthy"
  namespace: example
spec:
  selector:
     app: example-app
  type: NodePort
  ports:
  - port: 9991
    protocol: TCP
    targetPort: 8080